alias gti='git'
#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
#alias nethack-online='ssh nethack@nethack.alt.org ; clear'
#alias tron-online='ssh sshtron.zachlatta.com ; clear'
#alias glog='git log --oneline --graph --color --all --decorate'
alias x='exit' 2>/dev/null
alias la='ls -la' 2>/dev/null
alias atop='atop -f' 2>/dev/null
alias ..='cd ..'
alias ...='cd ../..'
alias tail='tail -n200'
